<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add an announcement' => '',
    'Admin' => '',
    'Announcements' => '',
    'Are you sure you want to delete this item?' => '',
    'Create' => '',
    'Create Announcement' => '',
    'Create an Announcement' => '',
    'Delete' => '',
    'Home' => '',
    'Reset' => '',
    'Save' => '',
    'Search' => '',
    'The requested page does not exist.' => '',
    'This is the admin homepage of the {title} module.' => '',
    'Update' => '',
    'Update Announcement: {name}' => '',
    'View the latest announcements' => '',
    'Yii2 Module Base' => '',
    'Yii2 Module Base Admin area' => '',
];
